### PR TITLE
Labels in timestop mode + bug fixes

### LINKED ISSUE #74: Objects are labelled when time is stopped
When time is stopped you can see which objects are what by hovering over them

### PR DESCRIPTION
**Pull request by ectodrop**
Closes
#74
#70 
#65 
#60

### CODE REVIEW

File: Assets/FragileGlass.cs [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+    public HoldableItemScriptableObject hammer;
+
+    public string GetLabel()
+    {
+        if (powerGenerator.drained && IsHoldingHammer())
+            return "Break Glass (E)";
+        if (!powerGenerator.drained && IsHoldingHammer())
+            return "Can't break when filled with liquid";
+        if (!powerGenerator.drained && !IsHoldingHammer())
+            return "Can't break when filled with liquid";
```
Comment (wang-henry) [inline Assets/FragileGlass.cs:18]:
```suggestion
        if (!powerGenerator.drained)
            return "Can't break when filled with liquid";
```

File: Assets/FragileGlass.cs [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    }
+    
+    private bool IsHoldingHammer()
+    {
+        return PickUpHoldScript.heldItemIdentifier == hammer;
+    }
+    
+    public void Interact()
+    {
+        Debug.Log("Here");
```
Comment (wang-henry) [inline Assets/FragileGlass.cs:29]:
```suggestion
```

File: Assets/Scripts/Menu.cs [hunk 3]
```diff
@@ -5,9 +5,17 @@
 
 public class Menu : MonoBehaviour
 {
+    public void OnTutorialButton()
+    {
+        SceneManager.LoadScene("Tutorial-Power");
+    }
+    public void OnTutorialButton1()
+    {
+        SceneManager.LoadScene("Tutorial-emily");
```
Comment (wang-henry) [inline Assets/Scripts/Menu.cs:14]: We should probably rename this tutorial scene or else it kind of implies its for testing purposes.

**Review by wang-henry — APPROVED** [review]
